export const LOCATION_OPTIONS = [
  { value: "W", label: "W - Whole", description: "Response involves the entire blot" },
  { value: "D", label: "D - Common Detail", description: "Common detail area" },
  { value: "Dd", label: "Dd - Unusual Detail", description: "Unusual detail area" },
  { value: "S", label: "S - White Space", description: "White space response" },
  { value: "DdS", label: "DdS - Detail + Space", description: "Unusual detail with white space" },
];

export const DETERMINANT_OPTIONS = [
  { value: "F", label: "F - Form", description: "Form only" },
  { value: "M", label: "M - Human Movement", description: "Human movement" },
  { value: "FM", label: "FM - Animal Movement", description: "Animal movement" },
  { value: "m", label: "m - Inanimate Movement", description: "Inanimate movement" },
  { value: "C", label: "C - Pure Color", description: "Pure color" },
  { value: "FC", label: "FC - Form-Color", description: "Form with color" },
  { value: "CF", label: "CF - Color-Form", description: "Color with form" },
  { value: "C'", label: "C' - Achromatic Color", description: "Black, white, gray" },
  { value: "FC'", label: "FC' - Form-Achromatic", description: "Form with achromatic color" },
  { value: "C'F", label: "C'F - Achromatic-Form", description: "Achromatic color with form" },
  { value: "T", label: "T - Texture", description: "Texture response" },
  { value: "FT", label: "FT - Form-Texture", description: "Form with texture" },
  { value: "TF", label: "TF - Texture-Form", description: "Texture with form" },
  { value: "V", label: "V - Vista", description: "Vista/depth" },
  { value: "FV", label: "FV - Form-Vista", description: "Form with vista" },
  { value: "VF", label: "VF - Vista-Form", description: "Vista with form" },
  { value: "Y", label: "Y - Shading", description: "Diffuse shading" },
  { value: "FY", label: "FY - Form-Shading", description: "Form with shading" },
  { value: "YF", label: "YF - Shading-Form", description: "Shading with form" },
  { value: "Fr", label: "Fr - Reflection", description: "Reflection" },
  { value: "rF", label: "rF - Reflection-Form", description: "Reflection with form" },
  { value: "FD", label: "FD - Form Dimension", description: "Form-based dimensionality" },
];

export const CONTENT_OPTIONS = [
  { value: "H", label: "H - Human", description: "Whole human figure" },
  { value: "(H)", label: "(H) - (Human)", description: "Fictional or mythological human" },
  { value: "Hd", label: "Hd - Human Detail", description: "Part of human" },
  { value: "(Hd)", label: "(Hd) - (Human Detail)", description: "Fictional human part" },
  { value: "Hx", label: "Hx - Human Experience", description: "Human emotion/experience" },
  { value: "A", label: "A - Animal", description: "Whole animal" },
  { value: "(A)", label: "(A) - (Animal)", description: "Fictional animal" },
  { value: "Ad", label: "Ad - Animal Detail", description: "Part of animal" },
  { value: "(Ad)", label: "(Ad) - (Animal Detail)", description: "Fictional animal part" },
  { value: "An", label: "An - Anatomy", description: "Anatomy, bones, organs" },
  { value: "Art", label: "Art - Art", description: "Art, painting, sculpture" },
  { value: "Ay", label: "Ay - Anthropology", description: "Anthropological, cultural items" },
  { value: "Bl", label: "Bl - Blood", description: "Blood" },
  { value: "Bt", label: "Bt - Botany", description: "Plants, trees, flowers" },
  { value: "Cg", label: "Cg - Clothing", description: "Clothing, garments" },
  { value: "Cl", label: "Cl - Clouds", description: "Clouds" },
  { value: "Ex", label: "Ex - Explosion", description: "Explosion, fireworks" },
  { value: "Fi", label: "Fi - Fire", description: "Fire, flames" },
  { value: "Fd", label: "Fd - Food", description: "Food items" },
  { value: "Ge", label: "Ge - Geography", description: "Maps, geographical features" },
  { value: "Hh", label: "Hh - Household", description: "Household items" },
  { value: "Ls", label: "Ls - Landscape", description: "Landscape, scenery" },
  { value: "Na", label: "Na - Nature", description: "Natural phenomena" },
  { value: "Sc", label: "Sc - Science", description: "Science, microscopic" },
  { value: "Sx", label: "Sx - Sex", description: "Sexual content" },
  { value: "Xy", label: "Xy - X-ray", description: "X-ray, transparency" },
  { value: "Idio", label: "Idio - Idiographic", description: "Unique, personal meaning" },
];
